services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - ./php/www:/var/www/html/
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8082:80
    env_file:
      - .env_wordpress
    volumes:
      - ./wordpress:/var/www/html
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
